# Use the official MySQL 8.0 image from Docker Hub
FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=amit1234

ENV MYSQL_DATABASE=springjdbc

EXPOSE 3306


COPY ./create_student_table.sql /docker-entrypoint-initdb.d/


